# -*- coding: utf-8 -*-
"""Selection Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1chBvhUbq0oXUcGsSK4HXZGa1MSjl7vxh
"""

def selection_sort(arr):
  min=0
  #fixing min position
  for i in range(len(arr)):
    
    min=i
    
    for j in range(i+1,len(arr)):
      if arr[j]<arr[min]:
        min=j
    
    arr[i],arr[min]=arr[min],arr[i]
  
  return arr

selection_sort([12939,10,709,12,1321,1920])

def selection_sort2(arr):
    
    # For every slot in array
    for fillslot in range(len(arr)-1,0,-1):
        positionOfMax=0
        # For every set of 0 to fillslot+1
        for location in range(1,fillslot+1):
            # Set maximum's location
            if arr[location]>arr[positionOfMax]:
                positionOfMax = location

        temp = arr[fillslot]
        arr[fillslot] = arr[positionOfMax]
        arr[positionOfMax] = temp
    return arr

selection_sort2([5,2,4,1,12])

